# Generated by Django 2.2 on 2021-03-23 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediate_cert', models.BinaryField(verbose_name='Intermediate attestation certificate')),
                ('leaf_cert', models.BinaryField(verbose_name='Attestation statement / leaf certificate')),
            ],
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ca.Attestation')),
            ],
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(verbose_name='Public key')),
            ],
        ),
        migrations.CreateModel(
            name='YubiKey',
            fields=[
                ('serial', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Serial number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.BinaryField(verbose_name='Certificate')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca.CA')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca.PublicKey')),
            ],
        ),
        migrations.AddField(
            model_name='attestation',
            name='pubkey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ca.PublicKey'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='yubikey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca.YubiKey'),
        ),
    ]
