# Generated by Django 2.2 on 2021-10-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='renewal_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ca.Certificate'),
        ),
    ]
