# Generated by Django 2.2 on 2021-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_certificate_renewal_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked',
            field=models.CharField(max_length=100, null=True, verbose_name='Reason for revocation'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='revoked',
            field=models.CharField(max_length=100, null=True, verbose_name='Reason for revocation'),
        ),
    ]
