# Generated by Django 2.2 on 2022-09-05 13:01

from django.db import migrations

def copy_yubikey_users(apps, schema_editor):
    YubiKey = apps.get_model('ca', 'YubiKey')
    Attestation = apps.get_model('ca', 'Attestation')
    for a in Attestation.objects.all():
        a.user = a.yubikey.user
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_attestation_user'),
    ]

    operations = [
        migrations.RunPython(copy_yubikey_users),
    ]
