# Generated by Django 2.2 on 2022-09-05 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_auto_20220905_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yubikey',
            name='user',
        ),
        migrations.AlterField(
            model_name='attestation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
