# Generated by Django 2.2 on 2024-05-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0006_auto_20220905_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SftpDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca.Certificate')),
            ],
        ),
    ]
